apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellofromnode-deployment
  labels:
    environment: dev
    app: hellofromnode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hellofromnode
  template:
    metadata:
      labels:
        app: hellofromnode
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: hellofromnode
          image: acrnativerogerio.azurecr.io/hellofromnode:v1.0
          resources:
            limits:
              cpu: "1"
              memory: "800Mi"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hellofromnode-service
spec:
  type: LoadBalancer
  selector:
    app: hellofromnode
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
